name: actual_budget

services:
  actual:
    container_name: actual_budget
    image: actualbudget/actual-server:latest
    user: "2000:3000"
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - /mnt/vault/services/actual_budget:/data
