title: Halfblown's Homelab
favicon: https://gethomepage.dev/img/favicon.ico
background:
  image: https://wallpaperbat.com/img/82218000-studio-ghibli-hd-wallpaper.jpg
  blur: sm
  saturate: 75
  brightness: 75
  opacity: 60

theme: dark
color: slate
headerStyle: boxed
layout:
  Media Services:
    style: row
    columns: 2
  "*Arr Services":
    style: row
    columns: 4
